# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-10 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicsite', '0005_auto_20181210_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
