# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-11 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='street',
            new_name='street_address',
        ),
    ]
